import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileProvider from "./core/providers/ProfileProvider";
const SideBar=dynamic(()=>import("./components/dashboard/SideBar"),{
  loading: ()=><p>Loading</p>,
});
// import SideBar from "./components/dashboard/SideBar";
import DashHeader from "./components/Dashheader/Dashheader";
import dynamic from "next/dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen overflow-hidden">
        <ProfileProvider>
          
          <div className="flex h-full">
            
            {/* SIDEBAR */}
            <SideBar />

            {/* RIGHT SECTION */}
            <div className="flex flex-col flex-1">
              
              {/* HEADER */}
              <DashHeader />

              {/* PAGE CONTENT */}
              <main className="flex-1 overflow-y-auto bg-gray-50 p-6">
                {children}
              </main>

            </div>
          </div>

        </ProfileProvider>
      </body>
    </html>
  );
}